name = "ArcadeLearningEnvironment"
uuid = "b7f77d8d-088d-5e02-8ac0-89aab2acc977"
version = "0.2.3"

[deps]
ArcadeLearningEnvironment_jll = "52cbb755-00ff-5a24-b23e-8a91c598877e"
LibArchive_jll = "1e303b3e-d4db-56ce-88c4-91e52606a1a8"
MD5 = "6ac74813-4b46-53a4-afec-0b5dc9d7885c"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
ArcadeLearningEnvironment_jll = "0.6"
LibArchive_jll = "3"
MD5 = "0.2"
julia = "1.3, 1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
